/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-12-09 16:31:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listaaasiakkaat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/tyyli.css\">\r\n");
      out.write("<script src=\"scripts/main.js\"></script>\r\n");
      out.write("<title>Asiakasohjelma JavaScriptilla </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onkeydown=\"tutkiKey(event)\">\r\n");
      out.write("<table id=\"listaus\">\r\n");
      out.write("	<thead>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th colspan=\"5\" id=\"ilmo\"></th>\r\n");
      out.write("			<th><a id=\"uusiAsiakas\" href=\"lisaaasiakas.jsp\">Lisää asiakas</a></th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th colspan=\"3\">Hakusana:</th>\r\n");
      out.write("			<th colspan=\"2\"><input type=\"text\" id=\"hakusana\"></th>\r\n");
      out.write("			<th><input type=\"button\" value=\"HAE\" id=\"hakunappi\" onclick=\"haeTiedot()\"></th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>Asiakasnumero</th>\r\n");
      out.write("			<th>Etunimi</th>\r\n");
      out.write("			<th>Sukunimi</th>\r\n");
      out.write("			<th>Puhelin</th>\r\n");
      out.write("			<th>Sposti</th>\r\n");
      out.write("			<th>Muuta/Poista</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</thead>\r\n");
      out.write("	<tbody id=\"tbody\">\r\n");
      out.write("	</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<script>\r\n");
      out.write("haeTiedot();	\r\n");
      out.write("document.getElementById(\"hakusana\").focus();//viedään kursori hakusana-kenttään sivun latauksen yhteydessä\r\n");
      out.write("\r\n");
      out.write("function tutkiKey(event){\r\n");
      out.write("	if(event.keyCode==13){//Enter\r\n");
      out.write("		haeTiedot();\r\n");
      out.write("	}		\r\n");
      out.write("}\r\n");
      out.write("//Funktio tietojen hakemista varten\r\n");
      out.write("//GET   /autot/{hakusana}\r\n");
      out.write("function haeTiedot(){	\r\n");
      out.write("	document.getElementById(\"tbody\").innerHTML = \"\";\r\n");
      out.write("	fetch(\"asiakkaat/\" + document.getElementById(\"hakusana\").value,{//Lähetetään kutsu backendiin\r\n");
      out.write("	      method: 'GET'\r\n");
      out.write("	    })\r\n");
      out.write("	.then(function (response) {//Odotetaan vastausta ja muutetaan JSON-vastaus objektiksi\r\n");
      out.write("		return response.json()	\r\n");
      out.write("	})\r\n");
      out.write("	.then(function (responseJson) {//Otetaan vastaan objekti responseJson-parametrissä		\r\n");
      out.write("		var asiakkaat = responseJson.asiakkaat;	\r\n");
      out.write("		var htmlStr=\"\";\r\n");
      out.write("		for(var i=0;i<asiakkaat.length;i++){			\r\n");
      out.write("        	htmlStr+=\"<tr>\";\r\n");
      out.write("        	htmlStr+=\"<td>\"+asiakkaat[i].asiakasID+\"</td>\";\r\n");
      out.write("        	htmlStr+=\"<td>\"+asiakkaat[i].etunimi+\"</td>\";\r\n");
      out.write("        	htmlStr+=\"<td>\"+asiakkaat[i].sukunimi+\"</td>\";\r\n");
      out.write("        	htmlStr+=\"<td>\"+asiakkaat[i].puhelin+\"</td>\";  \r\n");
      out.write("        	htmlStr+=\"<td>\"+asiakkaat[i].sposti+\"</td>\";  \r\n");
      out.write("        	htmlStr+=\"<td><a href='muutaasiakas.jsp?asiakasID=\"+asiakkaat[i].asiakasID+\"'>Muuta</a>&nbsp;\";\r\n");
      out.write("        	htmlStr+=\"<span class='poista' onclick=poista('\"+asiakkaat[i].asiakasID+\"')>Poista</span></td>\";\r\n");
      out.write("        	htmlStr+=\"</tr>\";        	\r\n");
      out.write("		}\r\n");
      out.write("		document.getElementById(\"tbody\").innerHTML = htmlStr;		\r\n");
      out.write("	})	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//Funktio tietojen poistamista varten. Kutsutaan backin DELETE-metodia ja välitetään poistettavan tiedon id. \r\n");
      out.write("//DELETE /autot/id\r\n");
      out.write("function poista(asiakasID){\r\n");
      out.write("	if(confirm(\"Poista asiakas \" + asiakasID +\"?\")){	\r\n");
      out.write("		fetch(\"asiakkaat/\"+ asiakasID,{//Lähetetään kutsu backendiin\r\n");
      out.write("		      method: 'DELETE'		      	      \r\n");
      out.write("		    })\r\n");
      out.write("		.then(function (response) {//Odotetaan vastausta ja muutetaan JSON-vastaus objektiksi\r\n");
      out.write("			return response.json()\r\n");
      out.write("		})\r\n");
      out.write("		.then(function (responseJson) {//Otetaan vastaan objekti responseJson-parametrissä		\r\n");
      out.write("			var vastaus = responseJson.response;		\r\n");
      out.write("			if(vastaus==0){\r\n");
      out.write("				document.getElementById(\"ilmo\").innerHTML= \"Asiakkaan poisto epäonnistui.\";\r\n");
      out.write("	        }else if(vastaus==1){	        	\r\n");
      out.write("	        	document.getElementById(\"ilmo\").innerHTML=\"Asiakkaan poisto onnistui.\";\r\n");
      out.write("				haeTiedot();        	\r\n");
      out.write("			}	\r\n");
      out.write("			setTimeout(function(){ document.getElementById(\"ilmo\").innerHTML=\"\"; }, 5000);\r\n");
      out.write("		})		\r\n");
      out.write("	}	\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
